# docker-compose.yml placeholder
version: '3'

services:
  service1:
    build: ./service_1
    container_name: golang_service
    ports:
      - "8001:8001"

  service2:
    build: ./service_2
    container_name: python_service
    ports:
      - "8002:8002"

  nginx:
    build: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
